version: '3'
services:
  zookeeper:
    image: zookeeper:3.8-temurin
    restart: always
    ports:
      - "2181:2181"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'ruok' | curl -s telnet://localhost:2181 || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - ZOO_CFG_EXTRA=4lw.commands.whitelist=ruok
  sekiro:
    build:
      context: .
      dockerfile: ./sekiro/Dockerfile
    restart: always
    ports:
      - "5620:5620"
    volumes:
      - ./logs:/opt/timed-task-caller/logs
  lv-you-lian-meng-lian-bot:
    build:
      context: .
      dockerfile: ./lv-you-lian-meng-lian-bot/Dockerfile
    restart: always
    ports:
      - "16649:16649"
  hui-jin-sheng-tai-bot:
    build:
      context: .
      dockerfile: ./hui-jin-sheng-tai-bot/Dockerfile
    restart: always
    ports:
      - "16650:16650"
  you-yu-shop-bot:
    build:
      context: .
      dockerfile: ./you-yu-shop-bot/Dockerfile
    restart: always
    ports:
      - "16651:16651"
  ku-you-bot:
    build:
      context: .
      dockerfile: ./ku-you-bot/Dockerfile
    restart: always
    ports:
      - "16652:16652"
  hi-pin-ji-bot:
    build:
      context: .
      dockerfile: ./hi-pin-ji-bot/Dockerfile
    restart: always
    ports:
      - "16653:16653"
  mei-ri-xiang-cun-bot:
    build:
      context: .
      dockerfile: ./mei-ri-xiang-cun-bot/Dockerfile
    restart: always
    ports:
      - "16654:16654"
  qi-cai-ren-sheng-bot:
    build:
      context: .
      dockerfile: ./qi-cai-ren-sheng-bot/Dockerfile
    restart: always
    ports:
      - "16655:16655"
  tao-fen-sheng-huo-bot:
    build:
      context: .
      dockerfile: ./tao-fen-sheng-huo-bot/Dockerfile
    restart: always
    ports:
      - "16656:16656"
  dian-dian-tiao-dong-bot:
    build:
      context: .
      dockerfile: ./dian-dian-tiao-dong-bot/Dockerfile
    restart: always
    ports:
      - "16657:16657"
  guo-tao-xian-sheng-bot:
    build:
      context: .
      dockerfile: ./guo-tao-xian-sheng-bot/Dockerfile
    restart: always
    ports:
      - "16658:16658"
  jing-yu-meta-bot:
    build:
      context: .
      dockerfile: ./jing-yu-meta-bot/Dockerfile
    restart: always
    ports:
      - "16659:16659"
  xing-ju-hui-bot:
    build:
      context: .
      dockerfile: ./xing-ju-hui-bot/Dockerfile
    restart: always
    ports:
      - "16660:16660"
  lian-you-bot:
    build:
      context: .
      dockerfile: ./lian-you-bot/Dockerfile
    restart: always
    ports:
      - "16661:16661"
  dong-mao-you-pin-bot:
    build:
      context: .
      dockerfile: ./dong-mao-you-pin-bot/Dockerfile
    restart: always
    ports:
      - "16662:16662"
  hong-yi-lv-you-bot:
    build:
      context: .
      dockerfile: ./hong-yi-lv-you-bot/Dockerfile
    restart: always
    ports:
      - "16663:16663"
  lin-cheng-jia-yuan-bot:
    build:
      context: .
      dockerfile: ./lin-cheng-jia-yuan-bot/Dockerfile
    ports:
      - "16664:16664"
  zhong-qi-shu-ju-lian-meng-bot:
    build:
      context: .
      dockerfile: ./zhong-qi-shu-ju-lian-meng-bot/Dockerfile
    ports:
      - "16665:16665"
  jin-hou-man-zuo-bot:
    build:
      context: .
      dockerfile: ./jin-hou-man-zuo-bot/Dockerfile
    ports:
      - "16666:16666"
  app-db:
    build:
      context: .
      dockerfile: ./app-db/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./app-db/data:/var/lib/postgresql/data
  app-backend:
    build:
      context: .
      dockerfile: ./app-backend/Dockerfile
    restart: always
    ports:
      - "16648:16648"
    depends_on:
      - "app-db"
      - "lv-you-lian-meng-lian-bot"
      - "hui-jin-sheng-tai-bot"
      - "you-yu-shop-bot"
      - "ku-you-bot"
      - "hi-pin-ji-bot"
      - "mei-ri-xiang-cun-bot"
      - "qi-cai-ren-sheng-bot"
      - "tao-fen-sheng-huo-bot"
      - "dian-dian-tiao-dong-bot"
      - "guo-tao-xian-sheng-bot"
      - "jing-yu-meta-bot"
      - "xing-ju-hui-bot"
      - "lian-you-bot"
      - "dong-mao-you-pin-bot"
      - "hong-yi-lv-you-bot"
      - "lin-cheng-jia-yuan-bot"
      - "zhong-qi-shu-ju-lian-meng-bot"
      - "jin-hou-man-zuo-bot"
      - "sekiro"
      - "zookeeper"
    volumes:
      - ./logs:/opt/app-backend/.logs
  timed-task-caller:
    build:
      context: .
      dockerfile: ./timed-task-caller/Dockerfile
    restart: always
    depends_on:
      - "app-backend"
    volumes:
      - ./logs:/opt/timed-task-caller/logs
